name: ie_tec_app
description: Flutter Monitor IE application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  thingsboard_pe_client: 1.0.7
  intl: ^0.17.0
  flutter_secure_storage: ^6.0.0
  flutter_speed_dial: ^6.0.0
  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  flutter_svg: ^1.1.3
  auto_size_text: ^3.0.0-nullsafety.0
  infinite_scroll_pagination: ^3.0.1
  fading_edge_scrollview: ^3.0.0
  stream_transform: ^2.0.0
  flutter_inappwebview:
    git:
      url: https://github.com/rshrc/flutter_inappwebview
      ref: master
  flutter_downloader: ^1.6.0
  permission_handler: ^8.0.0+2
  path_provider: ^2.0.2
  url_launcher: ^6.0.3
  image_picker: ^0.8.0
  mime: ^1.0.0
  logger: ^2.0.2+1
  qr_code_scanner: ^1.0.0
  device_info_plus: ^4.1.2
  geolocator: ^9.0.1
  material_design_icons_flutter: ^7.0.7296
  package_info: ^2.0.2
  dart_jsonwebtoken: ^2.2.0
  crypto: ^3.0.1
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^8.3.0
  uni_links: ^0.5.1
  flutter_html: ^3.0.0-alpha.5
  universal_html: ^2.0.8
  universal_platform: ^1.0.0+1
  preload_page_view: ^0.2.0
  flutter_localizations:
    sdk: flutter
  onesignal_flutter: ^3.5.0
  l10n_flutter: ^1.0.7
  intl_translation: ^0.18.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  intl: 0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ie_logo.png"
flutter_intl:
  enabled: true
